### ISSUE TITLE
Question: Settings for Members out of instance

### ISSUE THREAD

**Issue by charlesember** [tcwatson/SquadTracker#40]
Heyo,
I have just downloaded this module and i love it
this will make my raid commanding a lot easier, so thank you

Is there any setting i haven't found yet, that can show my squad members, even whem i am not in the same map instance as them ?

Ty
Charlie

**Comment by tcwatson** [comment]
Glad you are enjoying it! Unfortunately no, you can't see your squad mates
when they're in a different instance, due to the same limitation of ArcDPS
(which is how Squad Tracker gets data about your squad mates under the
hood).

It's been a long time for me since I've touched this or played much of
guild wars, so maybe there has been some update to Arc that I know about,
but until then, there isn't anything I can do to fix it sadly.

Have fun commanding!
